### ISSUE TITLE
How to start it?

### ISSUE THREAD

**Issue by ghost** [doublecluepon/SwfConduit#4]
I run twistd -ny swfconduit.tac and get No such file or directory: server.ini

The documentation doesn't mention needing a server.ini. Do I rename swfconduit.ini or what?

**Comment by preaction** [comment]
Looks like I forgot to push the changes that fixed this one. This is fixed in c4419f0adaf6c3d28cddbd83aa7446dc8781cf37. The more-correct error message is "cannot find module 'myproject'".

I'll release 1.0.2 once I add some documentation on that ini file (or, more accurately, remove that ini file completely, because the .tac file is just as capable of configuring the server, and it's in Python).

**Comment by ghost** [comment]
Yeah it's difficult to tell where to start even with the Failed to load application: No module named myproject error message. Beyond that, if the server did start out of box, it would be difficult to know how to setup a client to server message inside flash.

**Comment by preaction** [comment]
There's a tutorial in the docs, which I have to update now that I've changed how to configure servers (no .ini file anymore, thank god).

https://github.com/doublecluepon/SwfConduit/wiki/A-simple-chat-server

I'm trying to remember how to update the gh-pages docs right now.

**Comment by preaction** [comment]
Oh, I forgot I had also done a presentation on the content in that tutorial: http://preaction.github.io/Flex/SwfConduit.html

**Comment by preaction** [comment]
I've updated the wiki to add the presentation, and I've updated our README to point to the wiki for documentation.

The new swfconduit.tac file does not require a swfconduit.ini file, and I've removed it. I've added a much nicer way of configuring servers: You give the already-configured Server object directly to the Loader (1e1c41e051a35cde5d47b506b922adf91af19a87). 

Let me know if you have any more questions, and I'll update the documentation to address them.
